/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package placements;

import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author xyz
 */
public class PlacementLoadPrediction extends javax.swing.JFrame {

    
    String username="guest";
    /**
     * Creates new form HomeFrame
     */
    public PlacementLoadPrediction(String username) {
        this.username = username;
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * Creates new form ModuleCompletionAnalysisReport
     */
    public PlacementLoadPrediction() {
       
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        pnChart.setLayout(new java.awt.BorderLayout());
       
    }
 private DefaultCategoryDataset createDataset() {
        // same dataset for line chart and bar chart
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        if (jCourses.getSelectedIndex()==0) {
             dataset.addValue(2, "PGFAG", "PGFAG");
        dataset.addValue(1, "PGJS", "PGJS");
        dataset.addValue(3, "GNIIT", "GNIIT");
        
       
     
      
     }
       if (jCourses.getSelectedIndex()==1) {
             dataset.addValue(4, "PGFAG", "PGFAG");
        dataset.addValue(2, "PG.NET", "PG.NET");
        dataset.addValue(1, "ANIIT", "ANIIT");
        
       
     
      
     }
          if (jCourses.getSelectedIndex()==2) {
             dataset.addValue(1, "PGFAG", "PGFAG");
        dataset.addValue(1, "PGJS", "PGJS");
        dataset.addValue(2, "GNIIT", "GNIIT");
        
       
     
      
     }   if (jCourses.getSelectedIndex()==3) {
             dataset.addValue(5, "PGFAG", "PGFAG");
        dataset.addValue(2, "PG.NET", "PG.NET");
        dataset.addValue(4, "ANIIT", "ANIIT");
        
       
     
      
     }
        return dataset;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnChart = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jCourses = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jAppraisals = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        pnChart.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pnChart);
        pnChart.setBounds(40, 180, 860, 440);

        jButton1.setText("View Summary");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(640, 640, 110, 23);

        jLabel2.setText("Course Name : ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 640, 90, 14);

        jCourses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "This Month", "2 Months", "3 Months", "6 Months" }));
        getContentPane().add(jCourses);
        jCourses.setBounds(130, 640, 100, 20);

        jLabel3.setText("Appraisal Code : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 640, 100, 14);

        jAppraisals.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Appraisals", "INTERVIEW", "ENGLISH", "APTITUDE", "MACHINE" }));
        jAppraisals.setEnabled(false);
        getContentPane().add(jAppraisals);
        jAppraisals.setBounds(430, 640, 120, 20);

        jButton2.setText("View Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(760, 640, 120, 23);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 1, 10)); // NOI18N
        jLabel4.setText(username.toUpperCase());
        getContentPane().add(jLabel4);
        jLabel4.setBounds(480, 20, 80, 20);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/placements/logout.jpg"))); // NOI18N
        jButton6.setText("jButton6");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(903, 83, 70, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/placements/allpages.jpg"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1026, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String c,a;
    c = jCourses.getSelectedItem().toString();
    a = jAppraisals.getSelectedItem().toString();
    
    // create bar chart 
        JFreeChart barChart = ChartFactory.createBarChart(
                "Student Preparation Analysis",
                "Course", "Number of Students",
                createDataset(),
                PlotOrientation.HORIZONTAL,
                true, true, false);
        // set color
        CategoryPlot plot = (CategoryPlot) barChart.getPlot();
//        plot.getRenderer().setSeriesPaint(0, Color.BLUE);
        // create chart panel the add it to swing panel in  jframe
        ChartPanel chartPanel = new ChartPanel(barChart);
        pnChart.removeAll();        // clear panel before add new chart
        pnChart.add(chartPanel, BorderLayout.CENTER);
        pnChart.validate();          // refresh panel to display new chart
    
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        showTableData();
//          JFrame frame = new JFrame();
//      JPanel panel = new JPanel();
//         panel.setBorder(BorderFactory.createTitledBorder( BorderFactory.createEtchedBorder(), "Selection Analysis Report", TitledBorder.CENTER, TitledBorder.TOP));
//      String[][] rec = {
//         { "1", "Steve", "R200013300050","B200005","PGFAG","INTERVIEW","97" },
//         { "2", "Virat", "R200013300052","B200005","PGFAG","INTERVIEW","92" },
//         { "3", "Kane", "R200013300272","B200015","PGJS","ENGLISH","82" },
//         { "4", "David", "R200013300241","B200015","PGJS","ENGLISH","81" },
//         { "5", "Ben", "R200013300501","B200025","GNIIT","MACHINE","80" },
//         { "6", "Eion", "R200013300511","B200025","GNIIT","APTITUDE","70" },
//         { "7", "Ben", "R200013300501","B200025","GNIIT","ENGLISH","80" },
//         { "8", "Eion", "R200013300511","B200025","GNIIT","INTERVIEW","70" },
//          { "9", "Steve", "R200013300050","B200005","PGFAG","APTITUDE","67" },
//         { "10", "Virat", "R200013300052","B200005","PGFAG","APTITUDE","62" },
//         { "11", "Dhoni", "R200013300350","B200035","PG.NET","INTERVIEW","57" },
//         { "12", "Rohit", "R200013300715","B200005","PGFAG","MACHINE","55" },
//         { "13", "Kane", "R200013300272","B200015","PGJS","ENGLISH","82" },
//         { "14", "David", "R200013300241","B200015","PGJS","ENGLISH","81" },
//         { "15", "Ben", "R200013300501","B200025","GNIIT","MACHINE","80" },
//      };
//      String[] header = { "Rank", "Student Name", "Registration Code", "Batch Code","Course Name" , "Appraisal Name", "Score" };
//      JTable table = new JTable(rec, header);
//      table.setBounds(100, 100, 500, 400);
//      panel.add(new JScrollPane(table));
//      frame.add(panel);
//      frame.setSize(600, 500);
//      frame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
 if(JOptionPane.showConfirmDialog(null, "Are you sure ?") == JOptionPane.OK_OPTION){
                    setVisible(false);
                    dispose();
                    new MainFrame(username).setVisible(true);}

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        dispose();
        new EncoreLogin().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseClicked

    /**
     * @param args the command line arguments
     */
    
    
public void showTableData()
{
String[] columnNames = {"REGISTRATION_CODE","STUDENT_ID","STUDENT_NAME","CONTACT","EMAIL","ADDRESS","SCHOOL10","BOARD10","MARKS10","SCHOOL12","BOARD12","MARKS12","SCHOOL15","BOARD15","MARKS15"};
JFrame panel1 = new JFrame("Database Search Result");
 
panel1.setLayout(new BorderLayout());
//TableModel tm = new TableModel();
DefaultTableModel model = new DefaultTableModel();
model.setColumnIdentifiers(columnNames);
//DefaultTableModel model = new DefaultTableModel(tm.getData1(), tm.getColumnNames());
//table = new JTable(model);
JTable table = new JTable();
table.setModel(model);
table.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
table.setFillsViewportHeight(true);
JScrollPane scroll = new JScrollPane(table);
scroll.setHorizontalScrollBarPolicy(
JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
scroll.setVerticalScrollBarPolicy(
JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
//String textvalue = textbox.getText();
String REGISTRATION_CODE = "";
String STUDENT_ID= "";
String STUDENT_NAME= "";
String CONTACT= "";
String EMAIL= "";
String ADDRESS= "";
String SCHOOL10= "";
String BOARD10 = "";
String MARKS10 = "";
String SCHOOL12= "";
String BOARD12= "";
String MARKS12 = "";
String SCHOOL15= "";
String BOARD15= "";
String MARKS15 = "";
try
{
      String jdbcURL = "jdbc:h2:C:\\Users\\xyz\\Documents\\NetBeansProjects\\Placements\\db";
   String jdbcUsername = "sys";
   String jdbcPassword = "1234";

String driverName = "org.h2.Driver";
Class.forName(driverName);
Connection con = DriverManager.getConnection(jdbcURL, jdbcUsername, jdbcPassword);
String sql = "select * from plcload";
PreparedStatement ps = con.prepareStatement(sql);
ResultSet rs = ps.executeQuery();
int i =0;
while(rs.next())
{
REGISTRATION_CODE = rs.getString("REGISTRATION_CODE");
STUDENT_ID = rs.getString("STUDENT_ID");
STUDENT_NAME= rs.getString("STUDENT_NAME");
CONTACT= rs.getString("CONTACT");
EMAIL= rs.getString("EMAIL");
ADDRESS= rs.getString("ADDRESS");
SCHOOL10= rs.getString("SCHOOL10");
BOARD10 = rs.getString("BOARD10");
MARKS10 = rs.getString("MARKS10");
SCHOOL12= rs.getString("SCHOOL12");
BOARD12 = rs.getString("BOARD12");
MARKS12 = rs.getString("MARKS12");
SCHOOL15= rs.getString("SCHOOL15");
BOARD15 = rs.getString("BOARD15");
MARKS15 = rs.getString("MARKS15");
model.addRow(new Object[]{REGISTRATION_CODE, STUDENT_ID, STUDENT_NAME, CONTACT, EMAIL, ADDRESS, SCHOOL10, BOARD10, MARKS10, SCHOOL12, BOARD12, MARKS12, SCHOOL15, BOARD15, MARKS15});
i++;
}
if(i <1)
{
JOptionPane.showMessageDialog(null, "No Record Found","Error",
JOptionPane.ERROR_MESSAGE);
}
if(i ==1)
{
System.out.println(i+" Record Found");
}
else
{
System.out.println(i+" Records Found");
}
}
catch(Exception ex)
{
JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",
JOptionPane.ERROR_MESSAGE);
}
panel1.add(scroll);
panel1.setExtendedState(MAXIMIZED_BOTH);
panel1.setVisible(true);
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlacementLoadPrediction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlacementLoadPrediction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlacementLoadPrediction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlacementLoadPrediction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlacementLoadPrediction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jAppraisals;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jCourses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel pnChart;
    // End of variables declaration//GEN-END:variables
}
